import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Web3 TODO List",
  keywords: ["web3", "todo list", "blockchain", "dapp", "decentralized"],
  description: "Generated by create next app",
};

export default function RootLayout(props: {children: ReactNode}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body>
        <Providers>
          {props.children}
        </Providers>
      </body>
    </html>
  );
}
